services:
  - type: web
    name: whatsapp-system
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: PORT
        value: 3034
      - key: DB_URL
        value: mongodb://<tu_cluster_mongo>
      - key: SESSION_SECRET
        value: tu_clave_secreta

